version: '3.8'

services:
  frontend:
    container_name: ai-chatbot-frontend
    image: ghcr.io/atharvachaudhari9/ai-chatbot-supabase/frontend:latest
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    environment:
      - PYTHON_BACKEND_URL=http://backend:8000
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LOCAL_LLM_URL=http://ollama:11434
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    container_name: ai-chatbot-backend
    image: ghcr.io/atharvachaudhari9/ai-chatbot-supabase/backend:latest
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - qdrant
      - ollama
    restart: unless-stopped

  qdrant:
    container_name: ai-chatbot-qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  ollama:
    container_name: ai-chatbot-ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [gpu]
    restart: unless-stopped

  keycloak-db:
    container_name: ai-chatbot-keycloak-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_db_password
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak:
    container_name: ai-chatbot-keycloak
    image: quay.io/keycloak/keycloak:23.0
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_db_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_HOSTNAME: cognexa-ai.duckdns.org
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/themes:/opt/keycloak/themes

    depends_on:
      - keycloak-db
    restart: unless-stopped



volumes:
  qdrant_storage:
    name: qdrant_storage
  ollama_models:
    name: ollama_models
  keycloak_db_data:
    name: keycloak_db_data

